name: Python CI with Unittest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    env: 
      COVERAGE_FILE: coverage/.coverage
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set up permissions
        run: chmod +w coverage
      - name: Set up coverage folder
        run: export COVERAGE_FILE=/coverage/.coverage
        working-directory: /
      - name: Run Test
        run: python -m coverage run -m unittest -v
        working-directory: /
      - name: Coverage Report
        run: python -m coverage report
        working-directory: test